<img src="./assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Lab: Classification: Predicting Left-Handedness from Psychological Factors

---

One way to define the data science process is as follows:

1. Define the problem.
2. Obtain the data.
3. Explore the data.
4. Model the data.
5. Evaluate the model.
6. Answer the problem.

We'll walk through a full data science problem in this lab. 

---
## Step 1: Define The Problem.

You're currently a data scientist working at a university. A professor of psychology is attempting to study the relationship between personalities and left-handedness. They have tasked you with gathering evidence so that they may publish.

As a data scientist, you know that any real data science problem must be **specific** and **conclusively answerable**. For example:
- Bad data science problem: "What is the link between obesity and blood pressure?"
    - This is vague and is not conclusively answerable. That is, two people might look at the conclusion and one may say "Sure, the problem has been answered!" and the other may say "The problem has not yet been answered."
- Good data science problem: "Does an association exist between obesity and blood pressure?"
    - This is more specific and is conclusively answerable. The problem specifically is asking for a "Yes" or "No" answer. Based on that, two independent people should both be able to say either "Yes, the problem has been answered" or "No, the problem has not yet been answered."
- Excellent data science problem: "As obesity increases, how does blood pressure change?"
    - This is very specific and is conclusively answerable. The problem specifically seeks to understand the effect of one variable on the other.

### In the context of the left-handedness and personality example, what are three specific and conclusively answerable problems that you could answer using data science? 

> You might find it helpful to check out the codebook in the repo for some inspiration.

In [1]:
import pandas as pd
import numpy as np

---
## Step 2: Obtain the data.

### Read in the file titled "data.csv":
> Hint: Despite being saved as a .csv file, you won't be able to simply `pd.read_csv()` this data!

In [2]:
# library imports
df = pd.read_csv("./data/data.csv", sep='\t')
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3

---

## Step 3: Explore the data.

### Conduct background research:

Domain knowledge is irreplaceable. Figuring out what information is relevant to a problem, or what data would be useful to gather, is a major part of any end-to-end data science project! For this lab, you'll be using a dataset that someone else has put together, rather than collecting the data yourself.

Do some background research about personality and handedness. What features, if any, are likely to help you make good predictions? How well do you think you'll be able to model this? Write a few bullet points summarizing what you believe, and remember to cite external sources.

You don't have to be exhaustive here. Do enough research to form an opinion, and then move on.

> You'll be using the answers to Q1-Q44 for modeling; you can disregard other features, e.g. country, age, internet browser.

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4184 entries, 0 to 4183
Data columns (total 56 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           4184 non-null   int64
 1   Q2           4184 non-null   int64
 2   Q3           4184 non-null   int64
 3   Q4           4184 non-null   int64
 4   Q5           4184 non-null   int64
 5   Q6           4184 non-null   int64
 6   Q7           4184 non-null   int64
 7   Q8           4184 non-null   int64
 8   Q9           4184 non-null   int64
 9   Q10          4184 non-null   int64
 10  Q11          4184 non-null   int64
 11  Q12          4184 non-null   int64
 12  Q13          4184 non-null   int64
 13  Q14          4184 non-null   int64
 14  Q15          4184 non-null   int64
 15  Q16          4184 non-null   int64
 16  Q17          4184 non-null   int64
 17  Q18          4184 non-null   int64
 18  Q19          4184 non-null   int64
 19  Q20          4184 non-null   int64
 20  Q21          4184 non-null   int64
 21  Q22          4184 non-null   int64
 22  Q23          4184 non-null   int64
 23  Q24          4184 non-null   int64
 24  Q25          4184 non-null   int64
 25  Q26          4184 non-null   int64
 26  Q27          4184 non-null   int64
 27  Q28          4184 non-null   int64
 28  Q29          4184 non-null   int64
 29  Q30          4184 non-null   int64
 30  Q31          4184 non-null   int64
 31  Q32          4184 non-null   int64
 32  Q33          4184 non-null   int64
 33  Q34          4184 non-null   int64
 34  Q35          4184 non-null   int64
 35  Q36          4184 non-null   int64
 36  Q37          4184 non-null   int64
 37  Q38          4184 non-null   int64
 38  Q39          4184 non-null   int64
 39  Q40          4184 non-null   int64
 40  Q41          4184 non-null   int64
 41  Q42          4184 non-null   int64
 42  Q43          4184 non-null   int64
 43  Q44          4184 non-null   int64
 44  introelapse  4184 non-null   int64
 45  testelapse   4184 non-null   int64
 46  country      4184 non-null   str
 47  fromgoogle   4184 non-null   int64
 48  engnat       4184 non-null   int64
 49  age          4184 non-null   int64
 50  education    4184 non-null   int64
 51  gender       4184 non-null   int64
 52  orientation  4184 non-null   int64
 53  race         4184 non-null   int64
 54  religion     4184 non-null   int64
 55  hand         4184 non-null   int64
dtypes: int64(55), str(1)
memory usage: 1.8 MB

### Conduct exploratory data analysis on this dataset:

If you haven't already, be sure to check out the codebook in the repo, as that will help in your EDA process.

You might use this section to perform data cleaning if you find it to be necessary.

In [4]:
with pd.option_context('display.max_columns', None):
    display(df.describe())

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,Q31,Q32,Q33,Q34,Q35,Q36,Q37,Q38,Q39,Q40,Q41,Q42,Q43,Q44,introelapse,testelapse,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
count,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000
mean,1.962715,3.829589,2.846558,3.186902,2.865440,3.672084,3.216539,3.184512,2.761233,3.522945,2.748805,2.852772,2.657505,3.334130,3.168021,2.930210,2.564771,3.424952,2.928537,3.639818,2.867591,3.595124,3.861138,3.337237,1.999761,3.001434,2.730641,2.624044,2.543738,2.894359,3.002151,2.869503,2.741874,3.022228,3.074092,2.610660,3.465344,2.798757,2.569312,2.984226,3.385277,2.704828,2.676386,2.736616,347.808556,479.994503,1.576243,1.239962,30.370698,2.317878,1.654398,1.833413,5.013623,2.394359,1.190966
std,1.360291,1.551683,1.664804,1.476879,1.545798,1.342238,1.490733,1.387382,1.511805,1.242890,1.443078,1.556284,1.559575,1.522866,1.501683,1.575544,1.619010,1.413236,1.493122,1.414569,1.360858,1.354475,1.291425,1.426095,1.290747,1.480610,1.485883,1.481709,1.611428,1.477968,1.420032,1.659141,1.405670,1.562694,1.546400,1.409707,1.521460,1.413584,1.621772,1.483752,1.423055,1.544345,1.523097,1.471845,5908.901681,3142.178542,0.494212,0.440882,367.201726,0.874264,0.640915,1.303454,1.970996,2.184164,0.495357
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000,1.000000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,3.000000,1.000000,2.000000,1.000000,3.000000,2.000000,2.000000,1.000000,3.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,3.000000,2.000000,3.000000,3.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,6.000000,186.000000,1.000000,1.000000,18.000000,2.000000,1.000000,1.000000,5.000000,1.000000,1.000000
50%,1.000000,5.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,2.000000,4.000000,3.000000,4.000000,3.000000,4.000000,4.000000,3.000000,1.000000,3.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,4.000000,3.000000,2.000000,3.000000,4.000000,3.000000,3.000000,3.000000,12.000000,242.000000,2.000000,1.000000,21.000000,2.000000,2.000000,1.000000,6.000000,2.000000,1.000000
75%,3.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,5.000000,5.000000,5.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,35.000000,324.250000,2.000000,1.000000,27.000000,3.000000,2.000000,2.000000,6.000000,2.000000,1.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,252063.000000,119834.000000,2.000000,2.000000,23763.000000,4.000000,3.000000,5.000000,7.000000,7.000000,3.000000

In [5]:
df.shape

(4184, 56)

In [6]:
df = df[df['age']<100]

In [7]:
df.columns

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11',
       'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21',
       'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30', 'Q31',
       'Q32', 'Q33', 'Q34', 'Q35', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40', 'Q41',
       'Q42', 'Q43', 'Q44', 'introelapse', 'testelapse', 'country',
       'fromgoogle', 'engnat', 'age', 'education', 'gender', 'orientation',
       'race', 'religion', 'hand'],
      dtype='str')

In [8]:
for col in df.columns:
    df = df[df[col]!=0]

In [9]:
with pd.option_context('display.max_columns', None):
    display(df.describe())

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,Q31,Q32,Q33,Q34,Q35,Q36,Q37,Q38,Q39,Q40,Q41,Q42,Q43,Q44,introelapse,testelapse,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
count,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.00000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.00000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000,3479.000000
mean,1.977005,3.845070,2.861742,3.207531,2.892498,3.693590,3.235412,3.202357,2.768037,3.510204,2.752228,2.857143,2.686979,3.373096,3.18971,2.944237,2.588387,3.448117,2.949411,3.657373,2.874389,3.624317,3.89221,3.357574,2.010635,3.023283,2.744179,2.638977,2.566830,2.897959,3.018109,2.877264,2.749066,3.055188,3.103191,2.605921,3.492095,2.808278,2.589537,2.997988,3.414774,2.718022,2.685829,2.746479,268.495832,452.526588,1.574303,1.247485,24.586088,2.360736,1.688416,1.886462,5.089968,2.500431,1.189135
std,1.371500,1.539353,1.664370,1.467313,1.544974,1.331419,1.479610,1.380629,1.504240,1.233679,1.444231,1.554455,1.558899,1.503659,1.49340,1.567458,1.620081,1.392742,1.485709,1.401715,1.351857,1.333212,1.26170,1.406791,1.283841,1.471515,1.478456,1.480422,1.623594,1.470114,1.413793,1.657280,1.394965,1.547727,1.539022,1.403470,1.503449,1.398586,1.621082,1.474821,1.405902,1.539249,1.515457,1.463215,3411.185445,2673.702187,0.494519,0.431613,10.580152,0.837635,0.604812,1.277504,1.878026,2.171073,0.487789
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,41.000000,1.000000,1.000000,13.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,3.000000,1.000000,2.000000,1.000000,3.000000,2.000000,2.000000,1.000000,3.000000,1.000000,1.000000,1.000000,2.000000,2.00000,1.000000,1.000000,2.000000,2.000000,3.000000,2.000000,3.000000,3.00000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,6.000000,185.000000,1.000000,1.000000,18.000000,2.000000,1.000000,1.000000,6.000000,1.000000,1.000000
50%,1.000000,5.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,3.00000,3.000000,2.000000,4.000000,3.000000,4.000000,3.000000,4.000000,4.00000,3.000000,1.000000,3.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,4.000000,3.000000,2.000000,3.000000,4.000000,3.000000,3.000000,3.000000,12.000000,240.000000,2.000000,1.000000,21.000000,2.000000,2.000000,1.000000,6.000000,2.000000,1.000000
75%,3.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,5.00000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,5.000000,5.00000,5.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,5.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,35.500000,323.000000,2.000000,1.000000,27.000000,3.000000,2.000000,2.000000,6.000000,2.000000,1.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,112667.000000,93888.000000,2.000000,2.000000,86.000000,4.000000,3.000000,5.000000,7.000000,7.000000,3.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 3479 entries, 0 to 4183
Data columns (total 56 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           3479 non-null   int64
 1   Q2           3479 non-null   int64
 2   Q3           3479 non-null   int64
 3   Q4           3479 non-null   int64
 4   Q5           3479 non-null   int64
 5   Q6           3479 non-null   int64
 6   Q7           3479 non-null   int64
 7   Q8           3479 non-null   int64
 8   Q9           3479 non-null   int64
 9   Q10          3479 non-null   int64
 10  Q11          3479 non-null   int64
 11  Q12          3479 non-null   int64
 12  Q13          3479 non-null   int64
 13  Q14          3479 non-null   int64
 14  Q15          3479 non-null   int64
 15  Q16          3479 non-null   int64
 16  Q17          3479 non-null   int64
 17  Q18          3479 non-null   int64
 18  Q19          3479 non-null   int64
 19  Q20          3479 non-null   int64
 20  Q21          3479 non-null   int64
 21  Q22          3479 non-null   int64
 22  Q23          3479 non-null   int64
 23  Q24          3479 non-null   int64
 24  Q25          3479 non-null   int64
 25  Q26          3479 non-null   int64
 26  Q27          3479 non-null   int64
 27  Q28          3479 non-null   int64
 28  Q29          3479 non-null   int64
 29  Q30          3479 non-null   int64
 30  Q31          3479 non-null   int64
 31  Q32          3479 non-null   int64
 32  Q33          3479 non-null   int64
 33  Q34          3479 non-null   int64
 34  Q35          3479 non-null   int64
 35  Q36          3479 non-null   int64
 36  Q37          3479 non-null   int64
 37  Q38          3479 non-null   int64
 38  Q39          3479 non-null   int64
 39  Q40          3479 non-null   int64
 40  Q41          3479 non-null   int64
 41  Q42          3479 non-null   int64
 42  Q43          3479 non-null   int64
 43  Q44          3479 non-null   int64
 44  introelapse  3479 non-null   int64
 45  testelapse   3479 non-null   int64
 46  country      3479 non-null   str
 47  fromgoogle   3479 non-null   int64
 48  engnat       3479 non-null   int64
 49  age          3479 non-null   int64
 50  education    3479 non-null   int64
 51  gender       3479 non-null   int64
 52  orientation  3479 non-null   int64
 53  race         3479 non-null   int64
 54  religion     3479 non-null   int64
 55  hand         3479 non-null   int64
dtypes: int64(55), str(1)
memory usage: 1.5 MB

In [11]:
df.shape

(3479, 56)

### Calculate and interpret the baseline accuracy rate:

In [12]:
df['hand'].value_counts()

hand
1    2968
2     364
3     147
Name: count, dtype: int64

In [13]:
ba = len(df[df['hand']==2])/len(df['hand'])*100
print('baseline acccuracy for this case is: %.2f %%' %ba)

baseline acccuracy for this case is: 10.46 %

### Short answer questions:

In this lab you'll use K-nearest neighbors and logistic regression to model
handedness based off of psychological factors. 

Answer the following related questions; your answers may be in bullet points
**on your own words**

#### Describe the difference between regression and classification problems:

 **ANSWER** If we are predicting class, then we have a classification problem, if we predict number than problem is regression related.

#### Considering $k$-nearest neighbors, describe the relationship between $k$ and the bias-variance tradeoff:

**ANSWER**   
  
If we have huge bias, then model is too simple and underfitting, but if we have huge variance then we have overfitting and very complex model.
  
We need to adjust k in order to be not too small and too high.

#### Why do we often standardize predictor variables when using $k$-nearest neighbors?

**ANSWER** Because distance matters

#### Do you think we should standardize the explanatory variables for this problem? Why or why not?

In [14]:
# if we use Q1 to Q44 we do not to standardize them becasue they are at the same range

#### How do we settle on $k$ for a $k$-nearest neighbors model?

In [15]:
# k should be not be too small and to big. CV folding can tell us the best choice.

#### What is the default type of regularization for logistic regression as implemented in scikit-learn? (You might [check the documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html).)

In [16]:
# L2 is default, every column weight reduces close to zero but no to zero.

#### [Bonus - Optional] Describe the relationship between the scikit-learn `LogisticRegression` argument `C` and regularization strength:

In [17]:
#C is inverse of regularisation. C = 0 means that model underfitting, C = 100 overfitting. It's possible to use argument as Cs = 10 what means that 10 values odf C randomly will be taken as the argument

#### Describe the relationship between regularization strength and the bias-variance tradeoff:

In [18]:
# SEE ABOVE

#### Logistic regression is considered more interpretable than $k$-nearest neighbors. Explain why.

In [19]:
#Logistic regression is more interpretable because it learns one coefficient per feature whose sign and size directly show how that feature affects the prediction, while $k$-NN learns no parameters and simply votes among the nearest training points, so there is no summary of how each feature influences the outcome.

---

## Step 4 & 5 Modeling: $k$-nearest neighbors

### Train-test split your data:

Your explanatory variables should be all Q columns.

In [49]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler

In [25]:
df.columns

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11',
       'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21',
       'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30', 'Q31',
       'Q32', 'Q33', 'Q34', 'Q35', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40', 'Q41',
       'Q42', 'Q43', 'Q44', 'introelapse', 'testelapse', 'country',
       'fromgoogle', 'engnat', 'age', 'education', 'gender', 'orientation',
       'race', 'religion', 'hand'],
      dtype='str')

In [26]:
X = df[['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11',
       'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21',
       'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30', 'Q31',
       'Q32', 'Q33', 'Q34', 'Q35', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40', 'Q41',
       'Q42', 'Q43', 'Q44']]

y = df['hand']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### Create and fit four separate $k$-nearest neighbors models: 

### Model 1: one with $k = 3$:

In [30]:
model1 = KNeighborsClassifier(n_neighbors=3)

#### Model 2: one with $k = 5$

In [43]:
model2 = KNeighborsClassifier(n_neighbors=5)

#### Model 3: one with $k = 15$

In [44]:
model3 = KNeighborsClassifier(n_neighbors=15)

#### Model 4: one with $k = 25$:

In [45]:
model4 = KNeighborsClassifier(n_neighbors=25)

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

In [47]:
models = [model1, model2, model3, model4]
for model in models:
    model.fit(X_train, y_train)

    print("Train Score for k = %s is equal to %.5f" %(model.n_neighbors, model.score(X_train, y_train)))
    print("Test Score for k = %s is equal to %.5f" %(model.n_neighbors, model.score(X_test, y_test)))

Train Score for k = 3 is equal to 0.86561
Test Score for k = 3 is equal to 0.82040
Train Score for k = 5 is equal to 0.85519
Test Score for k = 5 is equal to 0.83764
Train Score for k = 15 is equal to 0.85196
Test Score for k = 15 is equal to 0.85776
Train Score for k = 25 is equal to 0.85196
Test Score for k = 25 is equal to 0.85776

---

## Step 4 & 5 Modeling: logistic regression

### Create and fit four separate logistic regression models:

*(Hint: Be careful with how you specify $\alpha$ in your model!)*
Note: You can use the same train and test data as above.

#### Model 1 : one with LASSO and $\alpha = 1$

In [50]:
model1 = Lasso(alpha=1)

#### Model 2 : one with LASSO and $\alpha = 10$

In [58]:
model2 = Lasso(alpha=10)

'Lasso'

#### Model 3 : one with RIDGE and $\alpha = 1$

In [59]:
model3 = Ridge(alpha=1)

#### Model 4 : one with RIDGE and $\alpha = 10$

In [63]:
model4= Ridge(alpha=10)

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

In [65]:
models = [model1, model2, model3, model4]
for model in models:
    model.fit(X_train, y_train)

    print("Train Score for model %s and alpha = %s is equal to %.15f" %(type(model).__name__, model.alpha, model.score(X_train, y_train)))
    print("Test Score for model %s and alpha = %s is equal to %.15f" %(type(model).__name__, model.alpha,  model.score(X_test, y_test)))
    print("*************************************************************************")

Train Score for model Lasso and alpha = 1 is equal to 0.000000000000000
Test Score for model Lasso and alpha = 1 is equal to -0.001422503095408
*************************************************************************
Train Score for model Lasso and alpha = 10 is equal to 0.000000000000000
Test Score for model Lasso and alpha = 10 is equal to -0.001422503095408
*************************************************************************
Train Score for model Ridge and alpha = 10 is equal to 0.028330861636140
Test Score for model Ridge and alpha = 10 is equal to -0.001869433959915
*************************************************************************
Train Score for model Ridge and alpha = 10 is equal to 0.028330861636140
Test Score for model Ridge and alpha = 10 is equal to -0.001869433959915
*************************************************************************

---

## Step 6: Answer the problem.

Are any of your models worth moving forward with? What are the "best" models?

In [ ]:
# NO ...