![](https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png) 

# Introduction to Time Series in Pandas

_Authors:_ Tim Book, Riley Dallas, Matt Brems

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

## Stock Data
We'll use [Yahoo! Finance](https://finance.yahoo.com/quote/AAPL) to get a few years worth of stock prices from Apple, Inc. (AAPL)

In [3]:
# Load data.
aapl = pd.read_csv('../data/AAPL.csv')
aapl.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-08-08,206.050003,207.809998,204.520004,207.250000,201.371887,22525500
1,2018-08-09,209.529999,209.779999,207.199997,208.880005,202.955643,23492600
2,2018-08-10,207.360001,209.100006,206.669998,207.529999,202.351089,24611200
3,2018-08-13,209.309998,210.949997,207.699997,208.869995,203.657639,25890900
4,2018-08-14,210.160004,210.559998,208.259995,209.750000,204.515747,20748000

In [4]:
# Change date column to be datetime dtype.
aapl['Date'] = pd.to_datetime(aapl['Date'])

Set the `Date` column to be the index.

Many time series methods and functions require the Pandas object's index to be the datetime. Thankfully this is a quick one-liner.

In [6]:
aapl.set_index('Date', inplace=True)

In [7]:
# We generally want our index to be sorted.
# This one is already sorted - but good to be sure.

aapl.sort_index(inplace=True)

## Filtering Time Series

Now that our `Date` column is the index, we can filter our data in unique ways. Try `aapl.loc['2018']` in the cell below:

In [8]:
aapl.loc['2018']

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-08-08,206.050003,207.809998,204.520004,207.250000,201.371887,22525500
2018-08-09,209.529999,209.779999,207.199997,208.880005,202.955643,23492600
2018-08-10,207.360001,209.100006,206.669998,207.529999,202.351089,24611200
2018-08-13,209.309998,210.949997,207.699997,208.869995,203.657639,25890900
2018-08-14,210.160004,210.559998,208.259995,209.750000,204.515747,20748000
...,...,...,...,...,...,...
2018-12-24,148.149994,151.550003,146.589996,146.830002,143.665421,37169200
2018-12-26,148.300003,157.229996,146.720001,157.169998,153.782547,58582500
2018-12-27,155.839996,156.770004,150.070007,156.149994,152.784531,53117100
2018-12-28,157.500000,158.520004,154.550003,156.229996,152.862808,42291400
2018-12-31,158.529999,159.360001,156.479996,157.740005,154.340271,35003500

You can also filter by month:

In [9]:
# Pull out all January 2019 data.

aapl[(aapl.index.year==2019)&(aapl.index.month==1)]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-01-02,154.889999,158.850006,154.229996,157.919998,154.516388,37039700
2019-01-03,143.979996,145.720001,142.000000,142.190002,139.125412,91312200
2019-01-04,144.529999,148.550003,143.800003,148.259995,145.064575,58607100
2019-01-07,148.699997,148.830002,145.899994,147.929993,144.741714,54777800
2019-01-08,149.559998,151.820007,148.520004,150.750000,147.500916,41025300
2019-01-09,151.289993,154.529999,149.630005,153.309998,150.005737,45099100
2019-01-10,152.500000,153.970001,150.860001,153.800003,150.485199,35780700
2019-01-11,152.880005,153.699997,151.509995,152.289993,149.007721,27023200
2019-01-14,150.850006,151.270004,149.220001,150.000000,146.767090,32439200
2019-01-15,150.270004,153.389999,150.050003,153.070007,149.770935,28710900
2019-01-16,153.080002,155.880005,153.000000,154.940002,151.600632,30569700
2019-01-17,154.199997,157.660004,153.259995,155.860001,152.500778,29821200
2019-01-18,157.500000,157.880005,155.979996,156.820007,153.440094,33751000
2019-01-22,156.410004,156.729996,152.619995,153.300003,149.995956,30394000
2019-01-23,154.149994,155.139999,151.699997,153.919998,150.602600,23130600
2019-01-24,154.110001,154.479996,151.740005,152.699997,149.408875,25441500
2019-01-25,155.479996,158.130005,154.320007,157.759995,154.359848,33535500
2019-01-28,155.789993,156.330002,153.660004,156.300003,152.931305,26192100
2019-01-29,156.250000,158.130005,154.110001,154.679993,151.346207,41587200
2019-01-30,163.250000,166.149994,160.229996,165.250000,161.688416,61109800
2019-01-31,166.110001,169.000000,164.559998,166.440002,162.852737,40739600

In [11]:
# Pull out all January data, across all years.
# Note this was always possible with datetime objects

aapl[aapl.index.month==1]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-01-02,154.889999,158.850006,154.229996,157.919998,154.516388,37039700
2019-01-03,143.979996,145.720001,142.000000,142.190002,139.125412,91312200
2019-01-04,144.529999,148.550003,143.800003,148.259995,145.064575,58607100
2019-01-07,148.699997,148.830002,145.899994,147.929993,144.741714,54777800
2019-01-08,149.559998,151.820007,148.520004,150.750000,147.500916,41025300
2019-01-09,151.289993,154.529999,149.630005,153.309998,150.005737,45099100
2019-01-10,152.500000,153.970001,150.860001,153.800003,150.485199,35780700
2019-01-11,152.880005,153.699997,151.509995,152.289993,149.007721,27023200
2019-01-14,150.850006,151.270004,149.220001,150.000000,146.767090,32439200
2019-01-15,150.270004,153.389999,150.050003,153.070007,149.770935,28710900
2019-01-16,153.080002,155.880005,153.000000,154.940002,151.600632,30569700
2019-01-17,154.199997,157.660004,153.259995,155.860001,152.500778,29821200
2019-01-18,157.500000,157.880005,155.979996,156.820007,153.440094,33751000
2019-01-22,156.410004,156.729996,152.619995,153.300003,149.995956,30394000
2019-01-23,154.149994,155.139999,151.699997,153.919998,150.602600,23130600
2019-01-24,154.110001,154.479996,151.740005,152.699997,149.408875,25441500
2019-01-25,155.479996,158.130005,154.320007,157.759995,154.359848,33535500
2019-01-28,155.789993,156.330002,153.660004,156.300003,152.931305,26192100
2019-01-29,156.250000,158.130005,154.110001,154.679993,151.346207,41587200
2019-01-30,163.250000,166.149994,160.229996,165.250000,161.688416,61109800
2019-01-31,166.110001,169.000000,164.559998,166.440002,162.852737,40739600
2020-01-02,296.239990,300.600006,295.190002,300.350006,298.292145,33870100
2020-01-03,297.149994,300.579987,296.500000,297.429993,295.392120,36580700
2020-01-06,293.790009,299.959991,292.750000,299.799988,297.745880,29596800
2020-01-07,299.839996,300.899994,297.480011,298.390015,296.345581,27218000
2020-01-08,297.160004,304.440002,297.160004,303.190002,301.112640,33019800
2020-01-09,307.239990,310.429993,306.200012,309.630005,307.508545,42527100
2020-01-10,310.600006,312.670013,308.250000,310.329987,308.203705,35161200
2020-01-13,311.640015,317.070007,311.149994,316.959991,314.788300,30383000
2020-01-14,316.700012,317.570007,312.170013,312.679993,310.537628,40488600
2020-01-15,311.850006,315.500000,309.549988,311.339996,309.206818,30480900
2020-01-16,313.589996,315.700012,312.089996,315.239990,313.080078,27207300
2020-01-17,316.269989,318.739990,315.000000,318.730011,316.546204,34454100
2020-01-21,317.190002,319.019989,316.000000,316.570007,314.401001,27710800
2020-01-22,318.579987,319.989990,317.309998,317.700012,315.523285,25458100
2020-01-23,317.920013,319.559998,315.649994,319.230011,317.042786,26118000
2020-01-24,320.250000,323.329987,317.519989,318.309998,316.129059,36634400
2020-01-27,310.059998,311.769989,304.880005,308.950012,306.833191,40485000
2020-01-28,312.600006,318.399994,312.190002,317.690002,315.513306,40558500
2020-01-29,324.450012,327.850006,321.380005,324.339996,322.117737,54057300
2020-01-30,320.540009,324.089996,318.750000,323.869995,321.650970,31685800
2020-01-31,320.929993,322.679993,308.290009,309.510010,307.389374,49897100

## Resampling

`df.resample()` is similar to `df.groupby()`, but with dates instead of categories.

In [16]:
# For each month 'M', calculate the average of
# each numeric value.

aapl.resample('ME').mean()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-08-31,214.618889,216.515555,213.503333,215.216668,209.767180,2.697328e+07
2018-09-30,222.331053,224.530526,220.077895,222.073685,216.531868,3.573537e+07
2018-10-31,221.200001,223.940871,217.874347,220.845652,215.334475,3.433689e+07
2018-11-30,191.819523,193.949523,188.700475,191.235714,186.944749,4.577745e+07
2018-12-31,165.243158,167.320001,161.891054,164.266317,160.725920,4.731171e+07
2019-01-31,153.608571,155.530478,151.947619,154.166190,150.843483,3.943273e+07
2019-02-28,171.392108,172.881580,170.531579,171.727893,168.558006,2.487056e+07
2019-03-31,183.223810,184.931906,181.410952,183.293810,180.112481,3.099911e+07
2019-04-30,199.866665,201.577143,198.630951,200.516191,197.035945,2.410084e+07
2019-05-31,190.938636,193.369544,189.205001,191.273637,188.428836,3.361166e+07
2019-06-30,192.664498,194.796001,191.233001,192.969000,190.349968,2.575936e+07
2019-07-31,205.051817,206.729545,203.914090,205.216364,202.431111,2.154350e+07
2019-08-31,205.262274,207.609546,202.849546,204.957728,202.738817,3.095794e+07
2019-09-30,217.727499,219.471001,215.939500,217.994999,215.853332,2.712836e+07
2019-10-31,234.929565,236.969131,232.945218,235.286521,232.974974,2.644794e+07
2019-11-30,261.693995,263.461501,260.242001,262.520503,260.569057,2.241658e+07
2019-12-31,275.391429,277.883810,273.868096,276.525710,274.631064,2.843803e+07
2020-01-31,311.170954,314.326188,308.831430,311.916191,309.779064,3.493298e+07
2020-02-29,310.313684,315.252633,306.726317,311.270522,309.713427,3.971488e+07
2020-03-31,261.073639,269.692725,254.846363,262.444092,261.264520,7.136446e+07
2020-04-30,271.811427,275.781429,268.084288,272.386188,271.161933,3.886773e+07
2020-05-31,308.885501,313.251500,306.381000,309.985503,309.227624,3.507603e+07
2020-06-30,344.541365,349.345001,340.642725,345.806360,345.183988,3.685179e+07
2020-07-31,381.669999,386.347272,377.062727,382.264999,381.577012,3.432382e+07
2020-08-31,440.256000,448.726001,436.214001,442.944000,442.306787,5.017284e+07

In [ ]:
# Calculate the sum over each day.

# What do you notice?

In [ ]:
# Calculate the sum over each quarter.

In [ ]:
# Calculate the sum over each quarter.
# BUT: change the index to be the start of each quarter.

## Rolling Statistics

With time series, we can "roll" statistics across time. For example, the rolling mean is the mean of a moving window across time periods.

We'll use a `.rolling()` method with a statistical function chained to it – just like with `.resample()` earlier. 

#### The Rolling Mean
For example, the 3-day rolling mean is calculated as:

$$ M_t = \frac{1}{3}\left(X_t + X_{t-1} + X_{t-2}\right) $$

In [ ]:
# Calculate the rolling average of the last 3 days.
# Notice the NAs generated!

## You Try:

Create a line chart for our data that includes:

* The adjusted closing price for AAPL
* The 12-day moving average of the closing price (the "fast" line)
* The 26-day moving average of the closing price (the "slow" line)

**Fun Fact:** You've just created a MACD chart - a simple trading strategy is to buy or sell a stock when the fast and slow line cross!

---
# Back to the deck!
---

## Backshifting and Diffing
---
**Backshifting** values in a column is simply sliding all the values back a day. It's the operation, for each day $t$, of doing:

$$BX_t = X_{t - 1}$$
 
For example:

| Date | Price | Backshifted Price |
| --- | --- | --- |
| Jan 1 | 100 | _NaN_ |
| Jan 2 | 110 | 100 |
| Jan 3 | 105 | 110 |
| Jan 4 | 108 | 105 |

**Vocabulary:** Backshifting is sometimes called "lagging" and the new columns called "lags". For example, the new column created in the above example is the "first lag".

In [ ]:
# Create a new column that's the backshifted "Open" column
aapl['open_lag1'] = aapl['Open'].shift()
aapl.head()

**Differencing** a column is taking today's value and subtracting yesterday's. Another way of putting it is subtracing today's value from today's _backshifted_ value. Mathematically, this is:

$$
\begin{align}
\nabla X_t &= X_t - X_{t - 1} \\
           &= X_t - BX_t
\end{align}
$$

For example:

| Date | Price | Backshifted Price | Diffed Price |
| --- | --- | --- | --- |
| Jan 1 | 100 | _NaN_ | _NaN_ |
| Jan 2 | 110 | 100 | 10 |
| Jan 3 | 105 | 110 | -5 |
| Jan 4 | 108 | 105 | 3 |

In [ ]:
# Create a new column that's the diffed "Open" column.
# Then, create a new column that's "Open" minus the lagged column we made above. What do you notice?

## You Try:

Create two **separate** plots:
* The closing price of AAPL over time
* The diffed closing price of AAPL over time

Specifications:
* Make sure the _x_-axes line up
* It must be one image with two separate graphs

# Stationarity

First, some new datasets.

In [ ]:
# Population of Australia 1971-1994
aus = pd.read_csv('data/residents.csv')
aus.set_index(pd.to_datetime(aus.date), inplace=True)
aus.drop(columns='date', inplace=True)
aus.head()

In [ ]:
# Mean annual temperature (Fahrenheight) in New Haven, CT 1912-1971
nh = pd.read_csv('data/nhtemp.csv')
nh.set_index('year', inplace=True)
nh.head()

Plot these time series. Are they stationary? (We're just eye-balling stationarity for now, we'll have an official hypothesis test in the next lesson.)

If not... can you achieve stationarity after diffing?

In [ ]:
# Absolutely not! Clear upward trend.

In [ ]:
# Yeah, kinda!

In [ ]:
# Maybe! Seems trendless enough.

In [ ]:
# Definitely after diffing once!

# ACF and PACF
Explore the ACF and PACF graphs for both `aus` and `nh`. What do you notice about them?

The Australian population increases quickly over time - so we don't see any seasonal autocorrelation, but we do some steadily decreasing autocorrelation implying the upward trend. We also see only lag-1 partial autocorrelation since the lag-1 autocorrelation is independent of any lag-2 correlation.

The annual temperature in New Haven, CT doesn't increase or decrease over time and doesn't exhibit any seasonality. This is exhibited by no detectable [partial] autocorrelations.

## You Try: Lung disease data

Take a look at the lung disease data imported below. Look at its plot, ACF, and PACF. Can you explain the notable parts of each graph?

In [ ]:
lung = pd.read_csv('data/lung-deaths.csv')
lung.date = pd.to_datetime(lung.date)
lung.set_index('date', inplace=True)
lung.head()

## BONUS CHALLENGE

For each year 1974 to 1979, plot the lung disease-related deaths on the same 12-month _x_-axis. Do you notice any interesting patterns?

Yes! It appears that more deaths occur in colder months.

# Conclusions and Takeaways

* A **time series** is a series of observations taken in equally spaced intervals. Often this means days, months, quarters, or years.
* We have **dependent data** - we're very much concerned with row-to-row relationships and operation.
* Next, we'll focus on **forecasting** future observations!